# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev496+g51aced8.d20221101'
__version_tuple__ = version_tuple = (0, 1, 'dev496', 'g51aced8.d20221101')
